[package]
name = "stupid_script"
version = "0.1.0"
description = "A simple interpreted programming language written in Rust."
license = "MIT"
repository = "https://github.com/flappibird123/Stupid-script"